### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by jmcarcell** [iLCSoft/LCFIVertex#11]
The last commit makes compiling with C++20 possible so for the next release a new tag would be needed, otherwise if it happens using C++20 the version picked up will not compile. I don't have permissions in iLCSoft to push or do anything so I can't do it
Many thanks!

For either @tmadlener or @andresailer

**Comment by tmadlener** [comment]
Done: https://github.com/iLCSoft/LCFIVertex/releases/tag/v00-09
